/**
 * Hairstyle Knowledge Base
 * Each entry maps face shapes, hair types, gender, and lifestyle
 * to specific hairstyle recommendations.
 */

const HAIRSTYLES = [
  // ── MALE ──────────────────────────────────────────────────────────────────
  {
    id: "textured-crop",
    name: "Textured Crop",
    gender: ["male"],
    suitableFaceShapes: ["Round", "Square", "Oval"],
    hairTypes: ["Straight", "Wavy"],
    lifestyles: ["Professional", "Casual", "Trendy"],
    description: "Short textured top with faded sides. Adds height and structure.",
    tags: ["short", "modern", "low-maintenance"],
  },
  {
    id: "undercut",
    name: "Undercut",
    gender: ["male"],
    suitableFaceShapes: ["Round", "Heart", "Oval"],
    hairTypes: ["Straight", "Wavy", "Curly"],
    lifestyles: ["Trendy", "Casual"],
    description: "Shaved sides with longer hair on top. Creates contrast and volume.",
    tags: ["edgy", "modern", "versatile"],
  },
  {
    id: "pompadour",
    name: "Pompadour",
    gender: ["male"],
    suitableFaceShapes: ["Round", "Square", "Oblong"],
    hairTypes: ["Straight", "Wavy"],
    lifestyles: ["Trendy", "Casual"],
    description: "Voluminous swept-back style with short sides. Classic and bold.",
    tags: ["classic", "volume", "statement"],
  },
  {
    id: "side-part",
    name: "Side Part",
    gender: ["male"],
    suitableFaceShapes: ["Square", "Oval", "Diamond", "Oblong"],
    hairTypes: ["Straight", "Wavy"],
    lifestyles: ["Professional", "Casual"],
    description: "Clean side-parted style. Timeless and office-appropriate.",
    tags: ["classic", "professional", "clean"],
  },
  {
    id: "quiff",
    name: "Quiff",
    gender: ["male"],
    suitableFaceShapes: ["Square", "Oval", "Round"],
    hairTypes: ["Straight", "Wavy"],
    lifestyles: ["Trendy", "Casual"],
    description: "Swept-up front with tapered sides. Modern and stylish.",
    tags: ["volume", "modern", "versatile"],
  },
  {
    id: "faux-hawk",
    name: "Faux Hawk",
    gender: ["male"],
    suitableFaceShapes: ["Round", "Heart", "Diamond"],
    hairTypes: ["Straight", "Wavy", "Curly"],
    lifestyles: ["Trendy"],
    description: "Central ridge of hair with shorter sides. Bold without commitment.",
    tags: ["edgy", "trendy", "bold"],
  },
  {
    id: "curly-undercut",
    name: "Curly Undercut",
    gender: ["male"],
    suitableFaceShapes: ["Round", "Oval", "Heart"],
    hairTypes: ["Curly", "Coily"],
    lifestyles: ["Casual", "Trendy"],
    description: "Natural curls on top with shaved sides. Embraces curl texture.",
    tags: ["curly", "natural", "modern"],
  },
  {
    id: "taper-fade",
    name: "Taper Fade",
    gender: ["male"],
    suitableFaceShapes: ["Oval", "Round", "Diamond", "Heart"],
    hairTypes: ["Straight", "Wavy", "Curly", "Coily"],
    lifestyles: ["Professional", "Casual", "Trendy"],
    description: "Gradual fade from top to sides. Clean and versatile.",
    tags: ["clean", "fade", "versatile"],
  },
  {
    id: "caesar-cut",
    name: "Caesar Cut",
    gender: ["male"],
    suitableFaceShapes: ["Oval", "Square", "Oblong"],
    hairTypes: ["Straight", "Wavy"],
    lifestyles: ["Professional", "Casual"],
    description: "Short horizontal fringe with uniformly short hair. Low maintenance.",
    tags: ["short", "low-maintenance", "classic"],
  },
  {
    id: "slick-back",
    name: "Slick Back",
    gender: ["male"],
    suitableFaceShapes: ["Oval", "Square", "Diamond"],
    hairTypes: ["Straight", "Wavy"],
    lifestyles: ["Professional", "Trendy"],
    description: "Hair combed straight back. Sophisticated and powerful look.",
    tags: ["sleek", "professional", "polished"],
  },
  {
    id: "buzz-cut",
    name: "Buzz Cut",
    gender: ["male"],
    suitableFaceShapes: ["Oval", "Square", "Diamond"],
    hairTypes: ["Straight", "Wavy", "Curly", "Coily"],
    lifestyles: ["Professional", "Casual"],
    description: "Uniformly short all around. Minimal effort, maximum confidence.",
    tags: ["minimal", "low-maintenance", "bold"],
  },

  // ── FEMALE ────────────────────────────────────────────────────────────────
  {
    id: "beach-waves",
    name: "Beach Waves",
    gender: ["female"],
    suitableFaceShapes: ["Square", "Heart", "Oval", "Diamond"],
    hairTypes: ["Wavy", "Straight"],
    lifestyles: ["Casual", "Trendy"],
    description: "Effortless tousled waves. Softens angular features beautifully.",
    tags: ["waves", "effortless", "feminine"],
  },
  {
    id: "bob",
    name: "Classic Bob",
    gender: ["female"],
    suitableFaceShapes: ["Oval", "Heart", "Square"],
    hairTypes: ["Straight", "Wavy"],
    lifestyles: ["Professional", "Casual"],
    description: "Jaw-length blunt cut. Timeless and structured.",
    tags: ["short", "classic", "structured"],
  },
  {
    id: "long-layers",
    name: "Long Layers",
    gender: ["female"],
    suitableFaceShapes: ["Round", "Square", "Oblong", "Heart"],
    hairTypes: ["Straight", "Wavy", "Curly"],
    lifestyles: ["Casual", "Professional", "Trendy"],
    description: "Long hair with cascading layers. Adds movement and dimension.",
    tags: ["long", "layers", "versatile"],
  },
  {
    id: "pixie-cut",
    name: "Pixie Cut",
    gender: ["female"],
    suitableFaceShapes: ["Oval", "Heart", "Diamond"],
    hairTypes: ["Straight", "Wavy"],
    lifestyles: ["Trendy", "Casual"],
    description: "Very short cropped style. Bold, confident, and low maintenance.",
    tags: ["short", "bold", "edgy"],
  },
  {
    id: "curtain-bangs",
    name: "Curtain Bangs",
    gender: ["female"],
    suitableFaceShapes: ["Round", "Square", "Oblong", "Heart"],
    hairTypes: ["Straight", "Wavy"],
    lifestyles: ["Casual", "Trendy"],
    description: "Centre-parted bangs that frame the face. Soft and romantic.",
    tags: ["bangs", "soft", "feminine"],
  },
  {
    id: "curly-lob",
    name: "Curly Lob",
    gender: ["female"],
    suitableFaceShapes: ["Oval", "Heart", "Square"],
    hairTypes: ["Curly", "Coily"],
    lifestyles: ["Casual", "Trendy"],
    description: "Long bob that embraces natural curls. Full and glamorous.",
    tags: ["curly", "medium-length", "natural"],
  },
  {
    id: "sleek-ponytail",
    name: "Sleek High Ponytail",
    gender: ["female"],
    suitableFaceShapes: ["Oval", "Square", "Diamond"],
    hairTypes: ["Straight", "Wavy"],
    lifestyles: ["Professional", "Trendy"],
    description: "High tight ponytail. Polished and elongates the face.",
    tags: ["updo", "sleek", "professional"],
  },
  {
    id: "afro",
    name: "Natural Afro",
    gender: ["female", "male"],
    suitableFaceShapes: ["Heart", "Diamond", "Oblong"],
    hairTypes: ["Coily"],
    lifestyles: ["Casual", "Trendy"],
    description: "Full natural afro. Celebrates natural texture and adds bold volume.",
    tags: ["natural", "volume", "bold"],
  },
];

module.exports = HAIRSTYLES;
